# https://medium.com/freestoneinfotech/simplifying-docker-compose-operations-using-makefile-26d451456d63
# https://stackoverflow.com/questions/67805969/wait-for-specific-container-when-using-docker-compose-up-d
up:
	docker-compose up -d 

down:
	docker-compose down

rm:
	docker-compose rm -f
